using System;
using System.Collections.Generic;
using System.Text;
using Palmmedia.ReportGenerator.Core.Logging;
using Palmmedia.ReportGenerator.Core.Parser.Filtering;

namespace Palmmedia.ReportGenerator.Core.Parser
{
    /// <summary>
    /// https://github.com/colszowka/simplecov
    /// https://github.com/dashingrocket/simplecov-cobertura
    /// SimpleCov is a code coverage tool for Ruby 1.9+;
    /// By default, it generates a HTML report: index.html
    /// In HTML footer, there is a generated by link with URL: https://github.com/colszowka/simplecov
    /// </summary>
    internal class SimpleCovParser : ParserBase
    {
        /// <summary>
        /// The Logger.
        /// </summary>
        private static readonly ILogger Logger = LoggerFactory.GetLogger(typeof(ParserBase));

        internal SimpleCovParser(IFilter assemblyFilter, IFilter classFilter, IFilter fileFilter) 
            : base(assemblyFilter, classFilter, fileFilter)
        {
        }
    }
}
